Rewrite scripts, fix up DNS crypto

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,20 +1,30 @@
 #!/usr/bin/env bash
 
-if [ "$1" != "" ]; then
-  target=$1
-  shift
-else
-  echo "Must specify a playbook!"
-  exit 1
-fi
+source bin/colors
 
+
+EVENT_PREFIX=deploy.fleet.
+
+target=$1; shift
 playbook=plays/${target}.yml
 
+if [ -z "${target}" ]; then
+  echo -e "${bold}${red}====> Playbook not specified${reset}"
+  exit 1
+fi
 if ! [ -f "${playbook}" ]; then
-  echo "Playbook ${target} does not exist!"
+  echo -e "${bold}${red}====> Playbook does not exist${reset}"
   exit 1
 fi
 
-bin/event deploy.fleet.${target}
+echo -e "${bold}${blue}====> Deploy fleet [${green}${target}${blue}]${reset}"
 
-ansible-playbook ${playbook} $@
+echo -e "${bold}${blue}----> Record event (${green}${EVENT_PREFIX}${target}${blue})${reset}"
+bin/event "${EVENT_PREFIX}${target}"
+
+echo -e "${bold}${blue}----> Run playbook (${green}${playbook}${blue})${reset}"
+if ansible-playbook ${playbook} $@; then
+    echo -e "${bold}${green}====> Deploy succeeded${reset}"
+else
+    echo -e "${bold}${red}====> Deploy failed${reset}"
+fi
diff --git a/bin/tinc-key b/bin/tinc-key
--- a/bin/tinc-key
+++ b/bin/tinc-key
@@ -1,11 +1,35 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+source bin/colors
+
 
 KEYS=files/all/tinc
 
-if ! [ -f $KEYS/$1.pub ]; then
-  openssl genrsa 4096 > $KEYS/$1.priv
-  openssl rsa -in $KEYS/$1.priv -pubout > $KEYS/$1.pub
-else
-  echo "Key for $1 already exists!"
+host=$1
+pubkey=$KEYS/${host}.pub
+privkey=$KEYS/${host}.priv
+
+if [ -f "${pubkey}" ]; then
+  echo -e "${bold}${red}====> Key already exists${reset}"
   exit 1
 fi
+
+echo -e "${bold}${blue}====> Generate RSA keyset [${green}${host}${blue}]${reset}"
+
+echo -e "${bold}${blue}----> Generate private key (${green}${privkey}${blue})${reset}"
+echo -en "${blue}"
+if ! openssl genrsa 4096 > ${privkey}; then
+  echo -e "${bold}${red}===> Key generation failed${reset}"
+  exit 1
+fi
+echo -en "${reset}"
+
+echo -e "${bold}${blue}----> Extract public key (${green}${pubkey}${blue})${reset}"
+echo -en "${blue}"
+if ! openssl rsa -in ${privkey} -pubout > ${pubkey}; then
+  echo -e "${bold}${red}===> Key extraction failed${reset}"
+  exit 1
+fi
+echo -en "${reset}"
+
+echo -e "${bold}${green}====> Keyset created${reset}"
